function figure1 = createfigure_p1b(xdata1, ydata1, zdata1, zdata2, zdata3, zdata4, flipang)
%CREATEFIGURE(xdata1, ydata1, zdata1, zdata2, zdata3, zdata4)
%  XDATA1:  contour x
%  YDATA1:  contour y
%  ZDATA1:  contour z
%  ZDATA2:  contour z
%  ZDATA3:  contour z
%  ZDATA4:  contour z

%  Auto-generated by MATLAB on 24-Oct-2023 18:09:12

% Create figure
figure1 = figure('Color',[1 1 1],'position',[44 582 1425 267]);
colormap(jet);

% Create axes
axes1 = axes('Parent',figure1,...
    'Position',[0.0471929824561401 0.138202247191011 0.15541993281075 0.790543071161049]);
hold(axes1,'on');

% Create contour
contour(xdata1,ydata1,zdata1,10,'Parent',axes1,'LineWidth',2); %,...
%     'LevelList',[0.451495309014226 0.462823545350668 0.474151781687111 0.485480018023553 0.496808254359996 0.508136490696438 0.519464727032881 0.530792963369323 0.542121199705766 0.553449436042208 0.564777672378651 0.576105908715093 0.587434145051536 0.598762381387978 0.610090617724421]);

% Create ylabel
ylabel('T2 (ms)');

% Create xlabel
xlabel('T1 (ms)');

% Create title
title(['Echo 6, Flip = ' num2str(flipang) 'deg']);

box(axes1,'on');
axis(axes1,'tight');
hold(axes1,'off');
% Set the remaining axes properties
set(axes1,'BoxStyle','full','FontSize',12,'Layer','top');
% Create colorbar
colorbar(axes1,'Position',...
    [0.207373394827274 0.138576779026217 0.0112280701754386 0.790262172284644]);

% Create axes
axes2 = axes('Parent',figure1,...
    'Position',[0.287695968645016 0.134456928838951 0.155419932810749 0.790543071161049]);
hold(axes2,'on');

% Create contour
contour(xdata1,ydata1,zdata2,10,'Parent',axes2,'LineWidth',2); %,...
%     'LevelList',[0.2557222017331 0.275985217926053 0.296248234119006 0.31651125031196 0.336774266504913 0.357037282697866 0.377300298890819 0.397563315083772 0.417826331276725 0.438089347469679 0.458352363662632 0.478615379855585 0.498878396048538 0.519141412241491 0.539404428434444]);

% Create ylabel
ylabel('T2 (ms)');

% Create xlabel
xlabel('T1 (ms)');

% Create title
title(['Echo 16, Flip = ' num2str(flipang) 'deg']);

box(axes2,'on');
axis(axes2,'tight');
hold(axes2,'off');
% Set the remaining axes properties
set(axes2,'BoxStyle','full','FontSize',12,'Layer','top');
% Create colorbar
colorbar(axes2,'Position',...
    [0.452285675529028 0.134831460674157 0.0112280701754386 0.790262172284644]);

% Create axes
axes3 = axes('Parent',figure1,...
    'Position',[0.541532288167224 0.138202247191011 0.15541993281075 0.790543071161049]);
hold(axes3,'on');

% Create contour
contour(xdata1,ydata1,zdata3,10,'Parent',axes3,'LineWidth',2); %,...
%     'LevelList',[0.114455914072065 0.137996211653056 0.161536509234047 0.185076806815038 0.208617104396029 0.23215740197702 0.255697699558011 0.279237997139001 0.302778294719992 0.326318592300983 0.349858889881974 0.373399187462965 0.396939485043956 0.420479782624947 0.444020080205938]);

% Create ylabel
ylabel('T2 (ms)');

% Create xlabel
xlabel('T1 (ms)');

% Create title
title(['Echo 32, Flip = ' num2str(flipang) 'deg']);

box(axes3,'on');
axis(axes3,'tight');
hold(axes3,'off');
% Set the remaining axes properties
set(axes3,'BoxStyle','full','FontSize',12,'Layer','top');
% Create colorbar
colorbar(axes3,'Position',...
    [0.703162868511483 0.142322097378277 0.0112280701754386 0.790262172284644]);

% Create axes
axes4 = axes('Parent',figure1,...
    'Position',[0.782737028742067 0.138202247191011 0.156648936170213 0.790543071161049]);
hold(axes4,'on');

% Create contour
contour(xdata1,ydata1,zdata4,10,'Parent',axes4,'LineWidth',2); %,...
%     'LevelList',[0.0600014762187644 0.0823237973970431 0.104646118575322 0.1269684397536 0.149290760931879 0.171613082110158 0.193935403288436 0.216257724466715 0.238580045644994 0.260902366823272 0.283224688001551 0.30554700917983 0.327869330358108 0.350191651536387 0.372513972714666]);

% Create ylabel
ylabel('T2 (ms)');

% Create xlabel
xlabel('T1 (ms)');

% Create title
title(['Echo 48, Flip = ' num2str(flipang) 'deg']);

box(axes4,'on');
axis(axes4,'tight');
hold(axes4,'off');
% Set the remaining axes properties
set(axes4,'BoxStyle','full','FontSize',12,'Layer','top');
% Create colorbar
colorbar(axes4,'Position',...
    [0.948426026406219 0.146067415730337 0.0112280701754386 0.790262172284644]);

